###############################################################################
###
### Copyright (c) 2021-2022 Artyom Beilis <artyomtnk@yahoo.com>
###
### MIT License, see LICENSE.TXT
###
###############################################################################
import glob
import re
import os
import argparse
import sys

re_inc = re.compile(r'\s*#\s*include\s*"([^"]*)"\s')

def preprocess_includes(src_file,search_dirs,is_src=True):
	result = []
	name = None
	if is_src:
		name = src_file
	else:
		for d in search_dirs:
			name = os.path.join(d,src_file)
			if os.path.exists(name):
				break
	with open(name,'r') as f:
		for l in f.readlines():
			m = re_inc.match(l);
			if m:
				result.append(preprocess_includes(m.group(1),search_dirs,False))
			else:
				result.append(l)
	return ''.join(result)
	
def get_sources(files,search_dirs):
	sources = dict()
	for search_dir in search_dirs:
		for d, dirs, files in os.walk(search_dir):
			if len(dirs) == 0:
				program_name = os.path.basename(d)
				program_entry_points = dict()
				for fn in files:
					fpath = os.path.join(d, fn)
					content = preprocess_includes(fpath, [d])
					if "void main()" in content:
						ep_name = os.path.splitext(fn)[0]
						program_entry_points[ep_name] = content
				if len(program_entry_points) > 0:
					sources[program_name] = program_entry_points
	return sources;

def make_cpp(sources, target):
	if True:
		content = """
/// Autogenerated, don't edit
#include <map>
#include <string>
namespace dlprim {
namespace gpu {
// Hacky way of using multiple entry points
std::map<std::string, std::map<std::string, std::string>> kernel_sources =
{
		"""
		for prg_name, entry_points in sources.items():
			content += f"\n	{{\n		\"{prg_name}\",\n		{{"
			for ep_name, ep_src in entry_points.items():
				content += "\n			{"
				content += f"\n				\"{ep_name}\","
				content += f"\n				R\"kern_src(\n{ep_src}\n				)kern_src\""
				content += "\n			},"
			content = content.strip(",")
			content += "\n		}"
			content += "\n	},"
		content = content.strip(",")
		content += "\n};\n} // end namespace gpu\n} // end namespace dlprim"
		#input()
		#raise NotImplementedError
		
		
		with open(target, "w") as f:
			f.write(content)
	else:
		with open(target,'w') as f:
			f.write(r"""
/// Autogenerated, don't edit
#include <map>
#include <string>
namespace dlprim {
namespace gpu {
// Hacky way of using multiple entry points
std::map<std::string, std::map<std::string, std::string>> kernel_sources =
{
			""")
			for name in sources:
				f.write('{"%s",' % name)
				chunk=16000
				src = sources[name]
				for sect in range(0,len(src),chunk):
					f.write(' R"kern_src(%s)kern_src" ' % src[sect:sect+chunk])
				f.write('},')
			f.write('};\n')
			f.write('}} // namespaces\n')


if __name__ == "__main__":
	parser=argparse.ArgumentParser()
	parser.add_argument('-I',action='append',default=[])
	parser.add_argument('-o',required = True)
	parser.add_argument('sources',nargs='*')
	args = parser.parse_args(sys.argv[1:])
	src = get_sources(args.sources,args.I)
	make_cpp(src,args.o)
